# When we close a milestone, create a draft release
name: Draft Release
on:
  milestone:
    types: [closed]

jobs:
  sync:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context.payload)

            const tag = 'TagName';
            const name = 'Release Name';
            const body = 'Testing body';
            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: name,
              draft: true,
              body: body
            });
