# When we close a milestone, create a draft release
name: Draft Release
on:
  milestone:
    types: [closed]

jobs:
  sync:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const milestone = context.payload.milestone;
            console.log(milestone)

            const issues = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              milestone: milestone.number
            });
            console.log(issues)
            const body = issues.data.map(i => i.title).join("\n");
            params = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v' + milestone.title,
              name: milestone.title,
              draft: true,
              body: body
            };
            const match = milestone.description.match(/branch:\s*([^\s]+)/);
            if (!!match) {
              params.target_commitish = match[1];
              console.log('Found target branch:', params.target_commitish);
            }
            await github.repos.createRelease(params);
