name: Ensure Milestone
on:
  pull_request_target:
    types: [closed, opened, reopened]
  pull_request:
    types: [opened, closed, reopened]

jobs:
  sync:
    name: Assign Milestone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context)
            if (!context.payload.pull_request.milestone) {
              milestones = await github.issues.listMilestones({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                sort: 'due_on',
                direction: 'asc'
              })

              if (milestones.data.length === 0) {
                console.log('There are no milestones, skipping.');
                return;
              }

              console.log(milestones)
              console.log(milestones[0])
              console.log(context.payload.pull_request)
              await github.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                milestone: milestones[0].number
              });
              core.setOutput('milestone', milestones[0]);
            }
